// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAucIvaMP0-ZkmFQA3btU5G0mTeqgJJ9Lk',
    appId: '1:982728142194:web:f5420c52e759873f5f41eb',
    messagingSenderId: '982728142194',
    projectId: 'sajilo-yatra-2bf06',
    authDomain: 'sajilo-yatra-2bf06.firebaseapp.com',
    storageBucket: 'sajilo-yatra-2bf06.appspot.com',
    measurementId: 'G-4L476ETVX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqsDPu_g-JX6Fj1zutywpP_gteqoiqo8s',
    appId: '1:982728142194:android:a2b05219729f5ce65f41eb',
    messagingSenderId: '982728142194',
    projectId: 'sajilo-yatra-2bf06',
    storageBucket: 'sajilo-yatra-2bf06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC72dYhKedJAf8P164OMajoL0gCi8x82pk',
    appId: '1:982728142194:ios:c2ee36fe10b448085f41eb',
    messagingSenderId: '982728142194',
    projectId: 'sajilo-yatra-2bf06',
    storageBucket: 'sajilo-yatra-2bf06.appspot.com',
    iosClientId: '982728142194-upq367gplinvecjljpoi17t58knmtvgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.sajiloYatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC72dYhKedJAf8P164OMajoL0gCi8x82pk',
    appId: '1:982728142194:ios:f4326bd6cd0cdd5a5f41eb',
    messagingSenderId: '982728142194',
    projectId: 'sajilo-yatra-2bf06',
    storageBucket: 'sajilo-yatra-2bf06.appspot.com',
    iosClientId: '982728142194-pd0racbilvnqq10ftqb26mvavqo8nuun.apps.googleusercontent.com',
    iosBundleId: 'com.example.sajiloYatra.RunnerTests',
  );
}
